[window]
padding = { x = 0, y = 0 }

[font]
# BlexMono FiraCode
normal = { family = "BlexMono Nerd Font Mono" }
bold = { family = "BlexMono Nerd Font Mono" }
italic = { family = "BlexMono Nerd Font Mono"}
bold_italic = { family = "BlexMono Nerd Font Mono"}
size = 14.0

[colors.primary]
background= '0x141821'
foreground= '0xcccccc'

[colors.normal]
black=   '0xe9e9ed'
red=     '0xf52a65'
green=   '0x587539'
yellow=  '0x8c6c3e'
blue=    '0x2e7de9'
magenta= '0x9854f1'
cyan=    '0x007197'
white=   '0x6172b0'

[colors.bright]
black=   '0xa1a6c5'
red=     '0xf52a65'
green=   '0x587539'
yellow=  '0x8c6c3e'
blue=    '0x2e7de9'
magenta= '0x9854f1'
cyan=    '0x007197'
white=   '0x3760bf'
