[general]
working_directory = "C:\\Users\\mdd"

[font]
size = 18
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[font.normal]
family = "Iosevka NFM"
style = "Regular"

[font.bold]
family = "Iosevka NFM"
style = "Bold"

[font.bold_italic]
family = "Iosevka NFM"
style = "Bold Italic"

[font.italic]
family = "Iosevka NFM"
style = "Italic"

[window]
# opacity = 0.9
dynamic_padding = true
padding = {x = 2, y = 0}
# decorations = "None"
option_as_alt = "OnlyLeft"
dimensions = { columns = 100, lines = 25 }

[terminal]
shell = "nu"

[mouse]
hide_when_typing = true

[cursor]
style = { shape ="Beam", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }

[keyboard]
bindings = [
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]

[colors.primary]
background = "#303446"
foreground = "#c6d0f5"
dim_foreground = "#838ba7"
bright_foreground = "#c6d0f5"

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"

[colors.vi_mode_cursor]
text = "#303446"
cursor = "#babbf1"

[colors.search.matches]
foreground = "#303446"
background = "#a5adce"

[colors.search.focused_match]
foreground = "#303446"
background = "#a6d189"

[colors.footer_bar]
foreground = "#303446"
background = "#a5adce"

[colors.hints.start]
foreground = "#303446"
background = "#e5c890"

[colors.hints.end]
foreground = "#303446"
background = "#a5adce"

[colors.selection]
text = "#303446"
background = "#f2d5cf"

[colors.normal]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#a5adce"

[[colors.indexed_colors]]
index = 16
color = "#ef9f76"

[[colors.indexed_colors]]
index = 17
color = "#f2d5cf"
