# configuration
set-option -g mouse on
set-option -q utf8 on
set-option -g status-position top
set-option -g default-terminal "tmux-256color"
set-option -a terminal-overrides ",*256col*:RGB"
set-option -g status-interval 2
set-option -g renumber-windows on
set-option -g base-index 1
set-option -g pane-base-index 1

set-option -g mode-keys vi
bind '%' split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Configuration Reloaded"
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
# colorscheme
# FG='#cccccc'
# BG='#161a24'
# G='#292c33'
# B='#47b38f'
# P='#89b4fa'
# Y='#cc7a29'

FG='#3760bf'
BG='#e1e2e7'
G='#d4d8da'
B='#2e7de9'
P='#7847bd'
Y='#8c6c3e'

set-option -g pane-active-border-style "fg=$P"
set-option -g pane-border-style "fg=$BG"
set-option -g message-style "bg=$BG,fg=$FG"
set-option -g status-style "bg=$BG,fg=$FG"
set-option -g status-justify left
set-option -g status-right-length 120

set-option -g status-left "#[fg=$G,bg=$BG]#[fg=$B,bg=$G]  #{?client_prefix,#[fg=$B bg=$G],#[fg=$P bg=$G]} #S #[fg=$G,bg=$BG]"
set-option -g status-right "#[fg=$G,bg=$BG]#[fg=$Y,bg=$G]  #[fg=$B,bg=$G] #{pane_current_path} #[fg=$G,bg=$BG]"
set-window-option -g window-status-format "#[fg=$G,bg=$BG]#[fg=$P,bg=$G]  #W #[fg=$G,bg=$BG]"
set-window-option -g window-status-current-format "#[fg=$G,bg=$BG]#[fg=$Y,bg=$G] #[fg=$B,bg=$G] #W #[fg=$G,bg=$BG]"
