# configuration
set-option -g mouse on
set-option -q utf8 on
set-option -g status-position top
set-option -g default-terminal "tmux-256color"
set-option -a terminal-overrides ",*256col*:RGB"
set-option -g status-interval 2
set-option -g renumber-windows on
set-option -g base-index 1
set-option -g pane-base-index 1

set-option -g mode-keys vi
bind '%' split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Configuration Reloaded"
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
# colorscheme
#night
# FG='#cccccc'
# BG='#161a24'
# SBG='#292c33'
# SFG='#47b38f'
# IF='#89b4fa'
# IG='#cc7a29'
#day
FG='#3760bf'
BG='#e1e2e7'
SBG='#2e7de9'
SFG='#fafafa'
IF='#8990b3'
IG='#d7af00'

set-option -g pane-active-border-style "fg=$IF"
set-option -g pane-border-style "fg=$BG"
set-option -g message-style "bg=$BG,fg=$FG"
set-option -g status-style "bg=$BG,fg=$FG"
set-option -g status-justify left
set-option -g status-right-length 120

set-option -g status-left "#[fg=$SBG,bg=$BG]#[fg=$SFG,bg=$SBG]  #{?client_prefix,#[fg=$SFG bg=$SBG],#[fg=$IF bg=$SBG]} #S #[fg=$SBG,bg=$BG]"
set-option -g status-right "#[fg=$SBG,bg=$BG]#[fg=$IG,bg=$SBG]  #[fg=$SFG,bg=$SBG] #{pane_current_path}#[fg=$SBG,bg=$BG]"
set-window-option -g window-status-format "#[fg=$SBG,bg=$BG]#[fg=$IF,bg=$SBG]  #W #[fg=$SBG,bg=$BG]"
set-window-option -g window-status-current-format "#[fg=$SBG,bg=$BG]#[fg=$IG,bg=$SBG] #[fg=$SFG,bg=$SBG] #W #[fg=$SBG,bg=$BG]"
