syntax enable
filetype on
filetype indent on
set t_Co=256
set number
"set relativenumber
set cursorline
set colorcolumn=80
set showmode
set showcmd
set encoding=utf-8
set list
set listchars=trail:·,tab:»~,nbsp:+
set mouse=a
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set showmatch
set hlsearch
set ignorecase
set smartcase
set incsearch
set nobackup
set noswapfile
set nowrap
set foldmethod=indent
set foldlevelstart=99
set fillchars=eob:\ 
set signcolumn=yes
"dark
"colorscheme habamax
"light
colorscheme shine


nmap <c-h> <c-w>h
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-l> <c-w>l
nmap <c-n> :bn<cr>
nmap <c-p> :bp<cr>
nmap <c-x>k :bd<cr>
nmap <a-d> :terminal<cr>
tmap <a-d> exit<cr>

imap <c-d> <del>
imap <c-b> <left>
imap <c-f> <right>
imap <c-a> <home>
imap <c-e> <end>
imap <c-k> <c-o>d$
imap <c-s> <esc>:w<cr>
imap <c-n> <down>
imap <c-p> <up>
imap <c-j> <c-o>o
imap <c-k> <c-o>O

cmap <c-d> <del>
cmap <c-b> <left>
cmap <c-f> <right>
cmap <c-a> <home>
cmap <c-e> <end>
