#! /usr/bin/bash

run() {
  if pidof "$1"; then
    pkill "$1"
  fi
  "$@"
}

run dunst -conf ~/.config/bspwm/dunstrc &
run sxhkd -c ~/.config/bspwm/sxhkdrc &
run polybar --reload -c ~/.config/bspwm/polybar.ini &
run nm-applet &
run fcitx5 &
run picom --config ~/.config/bspwm/picom.conf &
run flameshot &

feh --bg-scale ~/Pictures/background/4.png

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#A6E3A1"
bspc config normal_border_color  "#161A24"
bspc config active_border_color  "#A6E3A1"
bspc config presel_feedback_color "#161A24"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a QQ desktop='^8' state=floating follow=on
bspc rule -a microsoft-edge-stable desktop='^2'
bspc rule -a 'Clash for Windows' desktop='^9'
