local palette = {
  black = '#181a1f',
  bg0 = '#282c34',
  bg1 = '#31353f',
  bg2 = '#393f4a',
  bg3 = '#3b3f4c',
  bg_d = '#21252b',
  bg_blue = '#73b8f1',
  bg_yellow = '#ebd09c',
  fg = '#abb2bf',
  purple = '#c678dd',
  green = '#98c379',
  orange = '#d19a66',
  blue = '#61afef',
  yellow = '#e5c07b',
  cyan = '#56b6c2',
  red = '#e86671',
  grey = '#5c6370',
  light_grey = '#848b98',
  dark_cyan = '#2b6f77',
  dark_red = '#993939',
  dark_yellow = '#93691d',
  dark_purple = '#8a3fa0',
  diff_add = '#31392b',
  diff_delete = '#382b2c',
  diff_change = '#1c3448',
  diff_text = '#2c5372',
}

local groups = {
  { 'Normal', { fg = palette.fg, bg = palette.bg0 } },
  { 'Terminal', { fg = palette.fg, bg = palette.bg0 } },
  { 'EndOfBuffer', { fg = palette.bg0, bg = palette.bg0 } },
  { 'FoldColumn', { fg = palette.fg, bg = palette.bg1 } },
  { 'Folded', { fg = palette.fg, bg = palette.bg1 } },
  { 'SignColumn', { fg = palette.fg, bg = palette.bg0 } },
  { 'ToolbarLine', { fg = palette.fg } },
  { 'Cursor', { bg = palette.fg } },
  { 'CursorColumn', { bg = palette.bg1 } },
  { 'CursorLine', { bg = palette.bg1 } },
  { 'ColorColumn', { bg = palette.bg1 } },
  { 'CursorLineNr', { fg = palette.fg } },
  { 'LineNr', { fg = palette.grey } },
  { 'Conceal', { fg = palette.grey, bg = palette.bg1 } },
  { 'DiffAdd', { fg = palette.green, bg = palette.diff_add } },
  { 'DiffChange', { fg = palette.blue, bg = palette.diff_change } },
  { 'DiffDelete', { fg = palette.orange, bg = palette.diff_delete } },
  { 'DiffText', { fg = palette.orange, bg = palette.diff_text } },
  { 'DiffAdded', { fg = palette.green } },
  { 'DiffRemoved', { fg = palette.red } },
  { 'DiffFile', { fg = palette.cyan } },
  { 'DiffIndexLine', { fg = palette.Grey } },
  { 'Directory', { fg = palette.blue } },
  { 'ErrorMsg', { fg = palette.red, bold = true } },
  { 'WarningMsg', { fg = palette.yellow, bold = true } },
  { 'MoreMsg', { fg = palette.blue, bold = true } },
  { 'CurSearch', { fg = palette.bg0, bg = palette.orange } },
  { 'IncSearch', { fg = palette.bg0, bg = palette.orange } },
  { 'Search', { fg = palette.bg0, bg = palette.bg_yellow } },
  { 'Substitute', { fg = palette.bg0, bg = palette.green } },
  { 'MatchParen', { fg = palette.none, bg = palette.grey } },
  { 'NonText', { fg = palette.grey } },
  { 'Whitespace', { fg = palette.grey } },
  { 'SpecialKey', { fg = palette.grey } },
  { 'Pmenu', { fg = palette.fg, bg = palette.bg1 } },
  { 'PmenuSbar', { fg = palette.none, bg = palette.bg1 } },
  { 'PmenuSel', { fg = palette.bg0, bg = palette.bg_blue } },
  { 'WildMenu', { fg = palette.bg0, bg = palette.blue } },
  { 'PmenuThumb', { fg = palette.none, bg = palette.grey } },
  { 'Question', { fg = palette.yellow } },
  { 'SpellBad', { fg = palette.red, underline = true, sp = palette.red } },
  {
    'SpellCap',
    { fg = palette.yellow, underline = true, sp = palette.yellow },
  },
  { 'SpellLocal', { fg = palette.blue, underline = true, sp = palette.blue } },
  {
    'SpellRare',
    { fg = palette.purple, underline = true, sp = palette.purple },
  },
  { 'StatusLine', { fg = palette.fg, bg = palette.bg2 } },
  { 'StatusLineTerm', { fg = palette.fg, bg = palette.bg2 } },
  { 'StatusLineNC', { fg = palette.grey, bg = palette.bg1 } },
  { 'StatusLineTermNC', { fg = palette.grey, bg = palette.bg1 } },
  { 'TabLine', { fg = palette.fg, bg = palette.bg1 } },
  { 'TabLineFill', { fg = palette.grey, bg = palette.bg1 } },
  { 'TabLineSel', { fg = palette.bg0, bg = palette.fg } },
  { 'VertSplit', { fg = palette.bg3 } },
  { 'Visual', { bg = palette.bg3 } },
  { 'VisualNOS', { fg = palette.none, bg = palette.bg2, underline = true } },
  { 'QuickFixLine', { fg = palette.blue, underline = true } },
  { 'Debug', { fg = palette.yellow } },
  { 'debugPC', { fg = palette.bg0, bg = palette.green } },
  { 'debugBreakpoint', { fg = palette.bg0, bg = palette.red } },
  { 'ToolbarButton', { fg = palette.bg0, bg = palette.bg_blue } },
  { 'FloatBorder', { fg = palette.grey, bg = palette.bg1 } },
  { 'NormalFloat', { fg = palette.fg, bg = palette.bg1 } },
  { 'String', { fg = palette.green } },
  { 'Character', { fg = palette.orange } },
  { 'Number', { fg = palette.orange } },
  { 'Float', { fg = palette.orange } },
  { 'Boolean', { fg = palette.orange } },
  { 'Type', { fg = palette.yellow } },
  { 'Structure', { fg = palette.yellow } },
  { 'StorageClass', { fg = palette.yellow } },
  { 'Identifier', { fg = palette.red } },
  { 'Constant', { fg = palette.cyan } },
  { 'PreProc', { fg = palette.purple } },
  { 'PreCondit', { fg = palette.purple } },
  { 'Include', { fg = palette.purple } },
  { 'Keyword', { fg = palette.purple } },
  { 'Define', { fg = palette.purple } },
  { 'Typedef', { fg = palette.purple } },
  { 'Exception', { fg = palette.purple } },
  { 'Conditional', { fg = palette.purple } },
  { 'Repeat', { fg = palette.purple } },
  { 'Statement', { fg = palette.purple } },
  { 'Macro', { fg = palette.red } },
  { 'Error', { fg = palette.purple } },
  { 'Label', { fg = palette.purple } },
  { 'Special', { fg = palette.red } },
  { 'SpecialChar', { fg = palette.red } },
  { 'Function', { fg = palette.blue } },
  { 'Operator', { fg = palette.purple } },
  { 'Title', { fg = palette.cyan } },
  { 'Tag', { fg = palette.green } },
  { 'Delimiter', { fg = palette.light_grey } },
  { 'Comment', { fg = palette.grey, italic = true } },
  { 'SpecialComment', { fg = palette.grey, italic = true } },
  { 'Todo', { fg = palette.red, italic = true } },
  { '@annotation', { fg = palette.fg } },
  { '@attribute', { fg = palette.cyan } },
  { '@boolean', { fg = palette.orange } },
  { '@character', { fg = palette.orange } },
  { '@comment', { fg = palette.grey, italic = true } },
  { '@conditional', { fg = palette.purple } },
  { '@constant', { fg = palette.orange } },
  { '@constant.builtin', { fg = palette.orange } },
  { '@constant.macro', { fg = palette.orange } },
  { '@constructor', { fg = palette.yellow } },
  { '@error', { fg = palette.fg } },
  { '@exception', { fg = palette.purple } },
  { '@field', { fg = palette.cyan } },
  { '@float', { fg = palette.orange } },
  { '@function', { fg = palette.blue } },
  { '@function.builtin', { fg = palette.cyan } },
  { '@function.macro', { fg = palette.cyan } },
  { '@include', { fg = palette.purple } },
  { '@keyword', { fg = palette.purple } },
  { '@keyword.function', { fg = palette.purple } },
  { '@keyword.operator', { fg = palette.purple } },
  { '@label', { fg = palette.red } },
  { '@method', { fg = palette.blue } },
  { '@namespace', { fg = palette.yellow } },
  { '@none', { fg = palette.fg } },
  { '@number', { fg = palette.orange } },
  { '@operator', { fg = palette.fg } },
  { '@parameter', { fg = palette.red } },
  { '@parameter.reference', { fg = palette.fg } },
  { '@preproc', { fg = palette.purple } },
  { '@property', { fg = palette.cyan } },
  { '@punctuation.delimiter', { fg = palette.light_grey } },
  { '@punctuation.bracket', { fg = palette.light_grey } },
  { '@punctuation.special', { fg = palette.red } },
  { '@repeat', { fg = palette.purple } },
  { '@string', { fg = palette.green } },
  { '@string.regex', { fg = palette.orange } },
  { '@string.escape', { fg = palette.red } },
  { '@symbol', { fg = palette.cyan } },
  { '@tag', { fg = palette.purple } },
  { '@tag.attribute', { fg = palette.yellow } },
  { '@tag.delimiter', { fg = palette.purple } },
  { '@text', { fg = palette.fg } },
  { '@text.strong', { fg = palette.fg, bold = true } },
  { '@text.emphasis', { fg = palette.fg, italic = true } },
  { '@text.underline', { fg = palette.fg, underline = true } },
  { '@text.strike', { fg = palette.fg, strikethrough = true } },
  { '@text.title', { fg = palette.orange, bold = true } },
  { '@text.literal', { fg = palette.green } },
  { '@text.uri', { fg = palette.cyan, underline = true } },
  { '@text.todo', { fg = palette.red, italic = true } },
  { '@text.math', { fg = palette.fg } },
  { '@text.reference', { fg = palette.blue } },
  { '@text.environment', { fg = palette.fg } },
  { '@text.environment.name', { fg = palette.fg } },
  { '@text.diff.add', { fg = palette.green } },
  { '@text.diff.delete', { fg = palette.red } },
  { '@note', { fg = palette.fg } },
  { '@warning', { fg = palette.fg } },
  { '@danger', { fg = palette.fg } },
  { '@type', { fg = palette.yellow } },
  { '@type.builtin', { fg = palette.orange } },
  { '@variable', { fg = palette.red } },
  { '@variable.builtin', { fg = palette.yellow } },
  { 'IndentLine', { fg = palette.bg2 } },
  { 'SagaVariable', { fg = palette.green } },
  { 'GitSignsAdd', { fg = palette.green } },
  { 'GitSignsAddLn', { fg = palette.green } },
  { 'GitSignsAddNr', { fg = palette.green } },
  { 'GitSignsChange', { fg = palette.blue } },
  { 'GitSignsChangeLn', { fg = palette.blue } },
  { 'GitSignsChangeNr', { fg = palette.blue } },
  { 'GitSignsDelete', { fg = palette.red } },
  { 'GitSignsDeleteLn', { fg = palette.red } },
  { 'GitSignsDeleteNr', { fg = palette.red } },
  { 'TelescopeBorder', { fg = palette.red } },
  { 'TelescopePromptBorder', { fg = palette.cyan } },
  { 'TelescopeResultsBorder', { fg = palette.cyan } },
  { 'TelescopePreviewBorder', { fg = palette.cyan } },
  { 'TelescopeMatching', { fg = palette.orange, bold = true } },
  { 'TelescopePromptPrefix', { fg = palette.green } },
  { 'TelescopeSelection', { bg = palette.bg2 } },
  { 'TelescopeSelectionCaret', { fg = palette.yellow } },
  { 'LspCxxHlGroupEnumConstant', { fg = palette.orange } },
  { 'LspCxxHlGroupMemberVariable', { fg = palette.orange } },
  { 'LspCxxHlGroupNamespace', { fg = palette.blue } },
  { 'LspCxxHlSkippedRegion', { fg = palette.Grey } },
  { 'LspCxxHlSkippedRegionBeginEnd', { fg = palette.red } },
  { 'DiagnosticError', { fg = palette.red } },
  { 'DiagnosticHint', { fg = palette.purple } },
  { 'DiagnosticInfo', { fg = palette.cyan } },
  { 'DiagnosticWarn', { fg = palette.yellow } },
  { 'DiagnosticSignError', { fg = palette.red } },
  { 'DiagnosticSignWarn', { fg = palette.yellow } },
  { 'DiagnosticSignInfo', { fg = palette.cyan } },
  { 'DiagnosticSignHint', { fg = palette.purplr } },
  { 'DiagnosticUnderlineError', { undercurl = true, sp = palette.red } },
  { 'DiagnosticUnderlineHint', { undercurl = true, sp = palette.purple } },
  { 'DiagnosticUnderlineInfo', { undercurl = true, sp = palette.blue } },
  { 'DiagnosticUnderlineWarn', { undercurl = true, sp = palette.yellow } },
  { 'DiagnosticVirtualTextError', { fg = palette.dark_red } },
  { 'DiagnosticVirtualTextWarn', { fg = palette.dark_yellow } },
  { 'DiagnosticVirtualTextInfo', { fg = palette.dark_cyan } },
  { 'DiagnosticVirtualTextHint', { fg = palette.dark_purple } },
  { 'LspReferenceText', { bg = palette.bg2 } },
  { 'LspReferenceWrite', { bg = palette.bg2 } },
  { 'LspReferenceRead', { bg = palette.bg2 } },
  { 'LspCodeLens', { fg = palette.grey, italic = true } },
  { 'LspCodeLensSeparator', { fg = palette.grey } },
  { 'CmpItemAbbr', { fg = palette.fg } },
  {
    'CmpItemAbbrDeprecated',
    { fg = palette.light_grey, strikethrough = true },
  },
  { 'CmpItemAbbrMatch', { fg = palette.cyan } },
  { 'CmpItemAbbrMatchFuzzy', { fg = palette.cyan, underline = true } },
  { 'CmpItemMenu', { fg = palette.light_grey } },
  { 'cInclude', { fg = palette.blue } },
  { 'cStorageClass', { fg = palette.purple } },
  { 'cTypedef', { fg = palette.purple } },
  { 'cDefine', { fg = palette.cyan } },
  { 'cTSInclude', { fg = palette.blue } },
  { 'cTSConstant', { fg = palette.cyan } },
  { 'cTSConstMacro', { fg = palette.purple } },
  { 'cTSOperator', { fg = palette.purple } },
  { 'cppStatement', { fg = palette.purple, bold = true } },
  { 'cppTSInclude', { fg = palette.blue } },
  { 'cppTSConstant', { fg = palette.cyan } },
  { 'cppTSConstMacro', { fg = palette.purple } },
  { 'cppTSOperator', { fg = palette.purple } },
  { 'markdownBlockquote', { fg = palette.Grey } },
  { 'markdownBold', { fg = palette.none, bold = true } },
  { 'markdownBoldDelimiter', { fg = palette.Grey } },
  { 'markdownCode', { fg = palette.green } },
  { 'markdownCodeBlock', { fg = palette.green } },
  { 'markdownCodeDelimiter', { fg = palette.yellow } },
  { 'markdownH1', { fg = palette.red, bold = true } },
  { 'markdownH2', { fg = palette.purple, bold = true } },
  { 'markdownH3', { fg = palette.orange, bold = true } },
  { 'markdownH4', { fg = palette.red, bold = true } },
  { 'markdownH5', { fg = palette.purple, bold = true } },
  { 'markdownH6', { fg = palette.orange, bold = true } },
  { 'markdownHeadingDelimiter', { fg = palette.Grey } },
  { 'markdownHeadingRule', { fg = palette.Grey } },
  { 'markdownId', { fg = palette.yellow } },
  { 'markdownIdDeclaration', { fg = palette.red } },
  { 'markdownItalic', { fg = palette.none, italic = true } },
  { 'markdownItalicDelimiter', { fg = palette.grey, italic = true } },
  { 'markdownLinkDelimiter', { fg = palette.Grey } },
  { 'markdownLinkText', { fg = palette.red } },
  { 'markdownLinkTextDelimiter', { fg = palette.Grey } },
  { 'markdownListMarker', { fg = palette.red } },
  { 'markdownOrderedListMarker', { fg = palette.red } },
  { 'markdownRule', { fg = palette.purple } },
  { 'markdownUrl', { fg = palette.blue, underline = true } },
  { 'markdownUrlDelimiter', { fg = palette.Grey } },
  { 'markdownUrlTitleDelimiter', { fg = palette.green } },
  { 'latexTSInclude', { fg = palette.blue } },
  { 'latexTSFuncMacro', { fg = palette.fg } },
  { 'latexTSEnvironment', { fg = palette.cyan, bold = true } },
  { 'latexTSEnvironmentName', { fg = palette.yellow } },
  { 'texCmdEnv', { fg = palette.cyan } },
  { 'texEnvArgName', { fg = palette.yellow } },
  { 'latexTSTitle', { fg = palette.green } },
  { 'latexTSType', { fg = palette.blue } },
  { 'latexTSMath', { fg = palette.orange } },
  { 'texMathZoneX', { fg = palette.orange } },
  { 'texMathZoneXX', { fg = palette.orange } },
  { 'texMathDelimZone', { fg = palette.light_grey } },
  { 'texMathDelim', { fg = palette.purple } },
  { 'texMathOper', { fg = palette.red } },
  { 'texCmd', { fg = palette.purple } },
  { 'texCmdPart', { fg = palette.blue } },
  { 'texCmdPackage', { fg = palette.blue } },
  { 'texPgfType', { fg = palette.yellow } },
  { 'vimOption', { fg = palette.red } },
  { 'vimSetEqual', { fg = palette.yellow } },
  { 'vimMap', { fg = palette.purple } },
  { 'vimMapModKey', { fg = palette.orange } },
  { 'vimNotation', { fg = palette.red } },
  { 'vimMapLhs', { fg = palette.fg } },
  { 'vimMapRhs', { fg = palette.blue } },
  { 'vimVar', { fg = palette.fg } },
  { 'vimCommentTitle', { fg = palette.light_grey, italic = true } },
}
local function one()
  local g, api, opt = vim.g, vim.api, vim.opt
  g.terminal_color_0 = palette.black
  g.terminal_color_1 = palette.red
  g.terminal_color_2 = palette.green
  g.terminal_color_3 = palette.yellow
  g.terminal_color_4 = palette.blue
  g.terminal_color_5 = palette.purple
  g.terminal_color_6 = palette.cyan
  g.terminal_color_7 = palette.fg
  g.terminal_color_8 = palette.grey
  g.terminal_color_9 = palette.red
  g.terminal_color_10 = palette.green
  g.terminal_color_11 = palette.yellow
  g.terminal_color_12 = palette.blue
  g.terminal_color_13 = palette.purple
  g.terminal_color_14 = palette.cyan
  g.terminal_color_15 = palette.fg

  api.nvim_command('hi clear')
  opt.background = 'dark'
  opt.termguicolors = true
  g.colors_name = 'one'
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v[1], v[2])
  end
end

one()
