local keymap = vim.keymap.set
vim.g.mapleader = ' '
keymap('n', '<c-x>k', '<cmd>bdelete<cr>')
keymap('n', '<c-n>', '<cmd>bn<cr>')
keymap('n', '<c-p>', '<cmd>bp<cr>')
keymap('n', '<c-h>', '<c-w>h')
keymap('n', '<c-j>', '<c-w>j')
keymap('n', '<c-k>', '<c-w>k')
keymap('n', '<c-l>', '<c-w>l')
keymap('n', '<a-[>', '<cmd>vertical resize -5<cr>')
keymap('n', '<a-]>', '<cmd>vertical resize +5<cr>')

keymap('i', '<c-d>', '<del>')
keymap('i', '<c-b>', '<left>')
keymap('i', '<c-f>', '<right>')
keymap('i', '<c-a>', '<home>')
keymap('i', '<c-e>', '<end>')
keymap('i', '<c-k>', '<c-o>d$')
keymap('i', '<c-s>', '<esc>:w<cr>')
keymap('i', '<c-n>', '<down>')
keymap('i', '<c-p>', '<up>')
keymap('i', '<a-j>', '<c-o>o')
keymap('i', '<a-k>', '<c-o>O')

keymap('c', '<c-d>', '<del>')
keymap('c', '<c-b>', '<left>')
keymap('c', '<c-f>', '<right>')
keymap('c', '<c-a>', '<home>')
keymap('c', '<c-e>', '<end>')

keymap('n', 'gh', '<cmd>Lspsaga finder<cr>')
keymap({ 'n', 'v' }, 'ga', '<cmd>Lspsaga code_action<cr>')
keymap('n', 'gr', '<cmd>Lspsaga rename<cr>')
keymap('n', 'gp', '<cmd>Lspsaga peek_definition<cr>')
keymap('n', 'gd', '<cmd>Lspsaga goto_definition<cr>')
keymap('n', '<leader>sld', '<cmd>Lspsaga show_line_diagnostics<cr>')
keymap('n', '[c', '<cmd>Lspsaga show_cursor_diagnostics<cr>')
keymap('n', '[e', '<cmd>Lspsaga diagnostic_jump_prev<cr>')
keymap('n', ']e', '<cmd>Lspsaga diagnostic_jump_next<cr>')
keymap('n', '<leader>o', '<cmd>Lspsaga outline<cr>')
keymap('n', 'K', '<cmd>Lspsaga hover_doc<cr>')
keymap('n', '<leader>ci', '<cmd>Lspsaga incoming_calls<cr>')
keymap('n', '<leader>co', '<cmd>Lspsaga outgoing_calls<cr>')
keymap({ 'n', 't' }, '<A-d>', '<cmd>Lspsaga term_toggle<cr>')

keymap('n', 'gcc', '<cmd>ComComment<cr>')
keymap('x', 'gcc', ':ComComment<cr>')
keymap('n', 'gcj', '<cmd>ComAnnotation<cr>')

keymap('n', '<leader>ff', '<cmd>Telescope find_files<cr>')
keymap('n', '<leader>fg', '<cmd>Telescope live_grep<cr>')
keymap('n', '<leader>b', '<cmd>Telescope buffers<cr>')
keymap('n', '<leader>fh', '<cmd>Telescope help_tags<cr>')
keymap('n', '<leader>fb', '<cmd>Telescope file_browser<cr>')
keymap('n', '<leader>fm', '<cmd>lua vim.lsp.buf.format()<cr>')

keymap('n', '<leader>ss', '<cmd>SessionSave<cr>')
keymap('n', '<leader>sl', '<cmd>SessionLoad<cr>')

keymap('n', '[g', '<cmd>lua require("gitsigns").next_hunk()<cr>')
keymap('n', ']g', '<cmd>lua require("gitsigns").next_hunk()<cr>')
