local palette = {
  bg_dark = '#e9e9ec',
  -- bg = '#e1e2e7',
  bg = '#fafafa',
  bg_float = '#e9e9ec',
  bg_highlight = '#c4c8da',
  bg_popup = '#e9e9ec',
  bg_search = '#7890dd',
  bg_sidebar = '#e9e9ec',
  bg_statusline = '#e1e2e7',
  bg_visual = '#b6bfe2',
  black = '#e9e9ed',
  blue0 = '#7890dd',
  blue1 = '#188092',
  blue2 = '#07879d',
  blue = '#2e7de9',
  blue5 = '#006a83',
  blue6 = '#2e5857',
  blue7 = '#92a6d5',
  border = '#e9e9ed',
  border_highlight = '#2496ac',
  comment = '#848cb5',
  cyan = '#007197',
  dark3 = '#8990b3',
  dark5 = '#68709a',
  error = '#c64343',
  fg = '#3760bf',
  fg_dark = '#6172b0',
  fg_float = '#3760bf',
  fg_gutter = '#a8aecb',
  fg_sidebar = '#6172b0',
  diff_add = '#4197a4',
  diff_change = '#506d9c',
  diff_delete = '#c47981',
  diff_text = '#8990b3',
  gitSigns_add = '#399a96',
  gitSigns_change = '#6482bd',
  gitSigns_delete = '#c25d64',
  green1 = '#387068',
  green2 = '#38919f',
  green = '#587539',
  hint = '#118c74',
  info = '#07879d',
  magenta2 = '#d20065',
  magenta = '#9854f1',
  none = 'NONE',
  orange = '#b15c00',
  purple = '#7847bd',
  red1 = '#c64343',
  red = '#f52a65',
  teal = '#118c74',
  terminal_black = '#a1a6c5',
  warning = '#8c6c3e',
  yellow = '#8c6c3e',
}

local groups = {
  { 'Normal', { fg = palette.fg, bg = palette.bg } },
  { 'SignColumn', { fg = palette.fg_gutter } },
  { 'LineNr', { fg = palette.fg_gutter } },
  { 'EndOfBuffer', { fg = palette.bg, bg = palette.none } },
  { 'Search', { fg = palette.fg, bg = palette.bg_search } },
  { 'Visual', { bg = palette.bg_visual } },
  { 'ColorColumn', { bg = palette.black } },
  { 'Whitespace', { fg = palette.fg_gutter } },
  { 'VertSplit', { fg = palette.border } },
  { 'Title', { fg = palette.blue, bold = true } },
  { 'Cursorline', { bg = palette.bg_highlight } },
  { 'CursorLineNr', { fg = palette.dark5 } },
  { 'Pmenu', { bg = palette.bg_popup, fg = palette.fg } },
  { 'PmenuSel', { bg = palette.fg_sidebar } },
  { 'PmenuSbar', { fg = '#586e75' } },
  { 'PmenuThumb', { bg = palette.bg } },
  { 'PmenuKind', { bg = palette.bg_dark, fg = palette.yellow } },
  { 'PmenuKindSel', { link = 'PmenuSel' } },
  { 'PmenuExtra', { link = 'Pmenu' } },
  { 'PmenuExtraSel', { link = 'PmenuSel' } },
  { 'WildMenu', { link = 'Pmenu' } },
  {
    'StatusLine',
    { fg = palette.fg_sidebar, bg = palette.bg_statusline, bold = true },
  },
  { 'StatusLineNC', { fg = palette.fg_gutter, bg = palette.bg_statusline } },
  { 'WinBar', { bg = palette.none } },
  { 'WinBarNC', { bg = palette.none } },
  { 'Error', { fg = palette.error, bold = true } },
  { 'ErrorMsg', { link = 'Error' } },
  { 'TODO', { fg = palette.yellow } },
  { 'Conceal', { fg = palette.dark5, bg = palette.none } },
  { 'NonText', { link = 'Comment' } },
  { 'FloatBorder', { fg = palette.border_highlight, bg = palette.bg_float } },
  { 'FloatNormal', { link = 'Normal' } },
  { 'FloatShadow', { bg = palette.bg_dark } },
  { 'Folded', { fg = palette.blue, bold = true } },
  { 'FoldColumn', { link = 'SignColumn' } },
  { 'SpellBad', { fg = palette.error } },
  { 'SpellCap', { undercurl = true, fg = palette.warning } },
  { 'SpellRare', { undercurl = true, fg = palette.hint } },
  { 'SpellLocal', { undercurl = true } },
  { 'WarningMsg', { fg = palette.warning } },
  { 'MoreMsg', { fg = palette.blue } },
  { 'NvimInternalError', { fg = palette.error } },
  { 'Directory', { fg = palette.blue } },
  { 'Identifier', { fg = palette.magenta } },
  { '@variable', { fg = palette.fg } },
  { '@variable.builtin', { fg = palette.red } },
  { 'Constant', { fg = palette.orange } },
  { '@constant.builtin', { link = 'Constant' } },
  { '@constant.macro', { link = 'Constant' } },
  { '@namespace', { fg = palette.red } },
  { 'Keyword', { fg = palette.cyan } },
  { '@keyword.function', { link = 'Keyword' } },
  { '@keyword.return', { link = 'Keyword' } },
  { '@keyword.operator', { link = 'Operator' } },
  { 'Conditional', { link = 'Keyword' } },
  { 'Repeat', { link = 'Conditional' } },
  { 'Debug', { fg = palette.orange } },
  { 'Label', { fg = palette.purple } },
  { 'PreProc', { fg = palette.cyan } },
  { 'Include', { link = 'PreProc' } },
  { 'Exception', { fg = palette.purple } }, --
  { 'Statement', { fg = palette.magenta } },
  { 'SpecialKey', { fg = palette.dark3 } },
  { 'Special', { fg = palette.blue1 } },
  { 'Type', { fg = palette.blue1 } },
  { '@type.builtin', { link = 'Type' } },
  { '@type.definition', { link = 'Type' } },
  { '@type.qualifier', { link = 'KeyWord' } },
  { '@storageclass', { link = 'Keyword' } },
  { '@field', { fg = palette.green1 } },
  { '@property', { link = '@field' } },
  { 'Function', { fg = palette.blue } },
  { '@function.builtin', { link = 'Function' } },
  { '@function.call', { link = 'Function' } },
  { '@function.macro', { link = 'Function' } },
  { '@method', { link = 'Function' } },
  { '@method.call', { link = 'Function' } },
  { '@constructor', { fg = palette.magenta } },
  { '@parameter', { link = '@variable' } },
  { 'String', { fg = palette.green } },
  { 'Number', { fg = palette.purple } },
  { 'Float', { link = 'Number' } },
  { 'Boolean', { link = 'Constant' } },
  { 'Define', { link = 'PreProc' } },
  { 'Operator', { fg = palette.blue5 } },
  { 'Comment', { fg = palette.comment } },
  { '@punctuation.bracket', { fg = palette.fg_dark } },
  { '@punctuation.delimiter', { fg = palette.blue5 } },
  { '@tag.html', { fg = palette.orange } },
  { '@tag.attribute.html', { link = '@property' } },
  { '@tag.delimiter.html', { link = '@punctuation.delimiter' } },
  { '@tag.javascript', { link = '@tag.html' } },
  { '@tag.attribute.javascript', { link = '@tag.attribute.html' } },
  { '@tag.delimiter.javascript', { link = '@tag.delimiter.html' } },
  { '@tag.typescript', { link = '@tag.html' } },
  { '@tag.attribute.typescript', { link = '@tag.attribute.html' } },
  { '@tag.delimiter.typescript', { link = '@tag.delimiter.html' } },
  { '@text.reference.markdown_inline', { fg = palette.blue } },
  { 'DiffAdd', { fg = palette.diff_add, bg = palette.none } },
  { 'DiffChange', { fg = palette.diff_change } },
  { 'DiffDelete', { fg = palette.diff_delete } },
  { 'DiffText', { fg = palette.diff_text } },
  { '@text.diff.add.diff', { link = 'DiffAdd' } },
  { '@text.diff.delete.diff', { link = 'DiffDelete' } },
  { '@text.diff.change.diff', { link = 'DiffChange' } },
  { 'DiagnosticError', { link = 'Error' } },
  { 'DiagnosticWarn', { fg = palette.warning } },
  { 'DiagnosticInfo', { fg = palette.info } },
  { 'DiagnosticHint', { fg = palette.hint } },
  { 'DiagnosticSignError', { link = 'DiagnosticError' } },
  { 'DiagnosticSignWarn', { link = 'DiagnosticWarn' } },
  { 'DiagnosticSignInfo', { link = 'DiagnosticInfo' } },
  { 'DiagnosticSignHint', { link = 'DiagnosticHint' } },
  { 'DiagnosticUnderlineError', { undercurl = true } },
  { 'DiagnosticUnderlineWarn', { undercurl = true } },
  { 'DiagnosticUnderlineInfo', { undercurl = true } },
  { 'DiagnosticUnderlineHint', { undercurl = true } },
  { 'GitGutterAdd', { fg = palette.gitSigns_add } },
  { 'GitGutterChange', { fg = palette.gitSigns_change } },
  { 'GitGutterDelete', { fg = palette.git_delete } },
  { 'GitGutterChangeDelete', { fg = palette.gitSigns_delete } },
  {
    'TelescopePromptBorder',
    { bg = palette.bg_float, fg = palette.border_highlight },
  },
  { 'TelescopePromptNormal', { bg = palette.bg_float, fg = palette.orange } },
  {
    'TelescopeResultsBorder',
    { bg = palette.bg_float, fg = palette.fg_float },
  },
  {
    'TelescopePreviewBorder',
    { bg = palette.bg_float, fg = palette.fg_float },
  },
  { 'TelescopeResultsNormal', { fg = palette.fg_float } },
  { 'TelescopeSelectionCaret', { fg = palette.yellow } },
  { 'TelescopeMatching', { fg = palette.yellow } },
  { 'CursorWord', { bg = palette.bg_dark } },
  { 'IndentLine', { link = 'LineNr' } },
  { 'SagaVariable', { fg = palette.green } },
  { 'RapidFinished', { fg = palette.red, bold = true } },
  { 'RapidTake', { fg = palette.purple, bold = true } },
  { 'RapidDate', { fg = palette.purple, bold = true } },
  { 'RapidFile', { fg = palette.blue, bold = true } },
  { 'RapidTargetPos', { fg = palette.teal, bold = true } },
  { 'LspSignatureActiveParameter', { fg = palette.yellow, underline = true } },
  { 'netrwTreeBar', { link = 'Comment' } },
}

local g, api, opt = vim.g, vim.api, vim.opt
g.terminal_color_0 = palette.bg
g.terminal_color_1 = palette.red
g.terminal_color_2 = palette.green
g.terminal_color_3 = palette.yellow
g.terminal_color_4 = palette.blue
g.terminal_color_5 = palette.purple
g.terminal_color_6 = palette.cyan
g.terminal_color_7 = palette.fg
g.terminal_color_8 = palette.fg_float
g.terminal_color_9 = palette.red
g.terminal_color_10 = palette.green
g.terminal_color_11 = palette.yellow
g.terminal_color_12 = palette.blue
g.terminal_color_13 = palette.purple
g.terminal_color_14 = palette.cyan
g.terminal_color_15 = palette.fg

api.nvim_command('hi clear')
opt.background = 'light'
g.colors_name = 'day'
opt.termguicolors = true
for _, v in pairs(groups) do
  api.nvim_set_hl(0, v[1], v[2])
end
