local palette = {
  bg = '#161a24',
  bg_dim = '#191721',
  bg_lt = '#292c33',
  bg_alt = '#303030',
  fg = '#cccccc',
  fg_dim = '#989898',
  fg_alt = '#75715E',
  red = '#ff5f59',
  orange = '#cc7a29',
  yellow = '#ccad52',
  green = '#9eb336',
  cyan = '#52bccc',
  blue = '#5c95e6',
  purple = '#957acc',
  teal = '#47b38f',
  none = 'NONE',
}
local groups = {
  { 'Normal', { fg = palette.fg, bg = palette.bg } },
  { 'SignColumn', { bg = palette.bg } },
  { 'LineNr', { fg = palette.bg_alt } },
  { 'EndOfBuffer', { fg = palette.bg, bg = palette.none } },
  { 'Search', { fg = palette.yellow, reverse = true } },
  { 'Visual', { bg = palette.bg_alt } },
  { 'ColorColumn', { bg = palette.bg_alt } },
  { 'Whitespace', { fg = palette.bg_alt } },
  { 'VertSplit', { fg = palette.bg_alt } },
  { 'Title', { fg = palette.orange, bold = true } },
  { 'Cursorline', { bg = palette.bg_alt } },
  { 'CursorLineNr', { fg = palette.fg } },
  { 'Pmenu', { bg = palette.bg_dim, fg = palette.fg_dim } },
  { 'PmenuSel', { fg = palette.teal, bg = palette.bg_alt } },
  { 'PmenuSbar', { fg = '#586e75' } },
  { 'PmenuThumb', { bg = palette.bg } },
  { 'PmenuKind', { bg = palette.bg_dim, fg = palette.yellow } },
  { 'PmenuKindSel', { link = 'PmenuSel' } },
  { 'PmenuExtra', { link = 'Pmenu' } },
  { 'PmenuExtraSel', { link = 'PmenuSel' } },
  { 'WildMenu', { link = 'Pmenu' } },
  { 'StatusLine', { fg = palette.fg_dim, bg = palette.bg_lt, bold = true } },
  { 'StatusLineNC', { fg = palette.fg_dim, bg = palette.bg_alt } },
  { 'WinBar', { bg = palette.none } },
  { 'WinBarNC', { bg = palette.none } },
  { 'Error', { fg = palette.red, bold = true } },
  { 'ErrorMsg', { link = 'Error' } },
  { 'TODO', { fg = palette.cyan } },
  { 'Conceal', { fg = palette.blue, bg = palette.none } },
  { 'NonText', { link = 'Comment' } },
  { 'FloatBorder', { fg = palette.blue } },
  { 'FloatNormal', { link = 'Normal' } },
  { 'FloatShadow', { bg = palette.bg_alt } },
  { 'Folded', { fg = palette.bg, bold = true } },
  { 'FoldColumn', { link = 'SignColumn' } },
  { 'SpellBad', { fg = palette.red } },
  { 'SpellCap', { undercurl = true, fg = palette.red } },
  { 'SpellRare', { undercurl = true, fg = palette.purple } },
  { 'SpellLocal', { undercurl = true } },
  { 'WarningMsg', { fg = palette.red } },
  { 'MoreMsg', { fg = palette.green } },
  { 'NvimInternalError', { fg = palette.red } },
  { 'Directory', { fg = palette.blue } },
  { 'Identifier', { fg = palette.blue } },
  { '@variable', { fg = palette.fg } },
  { '@variable.builtin', { fg = palette.purple } },
  { 'Constant', { fg = palette.orange } },
  { '@constant.builtin', { link = 'Constant' } },
  { '@constant.macro', { link = 'Constant' } },
  { '@namespace', { fg = palette.cyan } },
  { 'Keyword', { fg = palette.green } },
  { '@keyword.function', { link = 'Keyword' } },
  { '@keyword.return', { link = 'Keyword' } },
  { '@keyword.operator', { link = 'Operator' } },
  { 'Conditional', { link = 'Keyword' } },
  { 'Repeat', { link = 'Conditional' } },
  { 'Debug', { fg = palette.orange } },
  { 'Label', { fg = palette.purple } },
  { 'PreProc', { fg = palette.purple } },
  { 'Include', { link = 'PreProc' } },
  { 'Exception', { fg = palette.purple } },
  { 'Statement', { fg = palette.purple } },
  { 'SpecialKey', { fg = palette.orange } },
  { 'Special', { fg = palette.orange } },
  { 'Type', { fg = palette.yellow } },
  { '@type.builtin', { link = 'Type' } },
  { '@type.definition', { link = 'Type' } },
  { '@type.qualifier', { link = 'KeyWord' } },
  { '@storageclass', { link = 'Keyword' } },
  { '@field', { fg = palette.cyan } },
  { '@property', { link = '@field' } },
  { 'Function', { fg = palette.blue } },
  { '@function.builtin', { link = 'Function' } },
  { '@function.call', { link = 'Function' } },
  { '@function.macro', { link = 'Function' } },
  { '@method', { link = 'Function' } },
  { '@method.call', { link = 'Function' } },
  { '@constructor', { fg = palette.orange } },
  { '@parameter', { link = '@variable' } },
  { 'String', { fg = palette.teal } },
  { 'Number', { fg = palette.purple } },
  { 'Float', { link = 'Number' } },
  { 'Boolean', { link = 'Constant' } },
  { 'Define', { link = 'PreProc' } },
  { 'Operator', { fg = palette.fg_dim } },
  { 'Comment', { fg = palette.fg_alt } },
  { '@punctuation.bracket', { fg = palette.fg_dim } },
  { '@punctuation.delimiter', { fg = palette.fg_dim } },
  { '@tag.html', { fg = palette.orange } },
  { '@tag.attribute.html', { link = '@property' } },
  { '@tag.delimiter.html', { link = '@punctuation.delimiter' } },
  { '@tag.javascript', { link = '@tag.html' } },
  { '@tag.attribute.javascript', { link = '@tag.attribute.html' } },
  { '@tag.delimiter.javascript', { link = '@tag.delimiter.html' } },
  { '@tag.typescript', { link = '@tag.html' } },
  { '@tag.attribute.typescript', { link = '@tag.attribute.html' } },
  { '@tag.delimiter.typescript', { link = '@tag.delimiter.html' } },
  { '@text.reference.markdown_inline', { fg = palette.blue } },
  { 'DiffAdd', { fg = palette.teal, bg = palette.none } },
  { 'DiffChange', { fg = palette.blue } },
  { 'DiffDelete', { fg = palette.orange } },
  { 'DiffText', { fg = palette.orange } },
  { '@text.diff.add.diff', { link = 'DiffAdd' } },
  { '@text.diff.delete.diff', { link = 'DiffDelete' } },
  { '@text.diff.change.diff', { link = 'DiffChange' } },
  { 'DiagnosticError', { link = 'Error' } },
  { 'DiagnosticWarn', { fg = palette.yellow } },
  { 'DiagnosticInfo', { fg = palette.blue } },
  { 'DiagnosticHint', { fg = palette.cyan } },
  { 'DiagnosticSignError', { link = 'DiagnosticError' } },
  { 'DiagnosticSignWarn', { link = 'DiagnosticWarn' } },
  { 'DiagnosticSignInfo', { link = 'DiagnosticInfo' } },
  { 'DiagnosticSignHint', { link = 'DiagnosticHint' } },
  { 'DiagnosticUnderlineError', { undercurl = true } },
  { 'DiagnosticUnderlineWarn', { undercurl = true } },
  { 'DiagnosticUnderlineInfo', { undercurl = true } },
  { 'DiagnosticUnderlineHint', { undercurl = true } },
  { 'GitGutterAdd', { fg = palette.teal } },
  { 'GitGutterChange', { fg = palette.blue } },
  { 'GitGutterDelete', { fg = palette.red } },
  { 'GitGutterChangeDelete', { fg = palette.red } },
  { 'TelescopePromptBorder', bg = palette.bg_alt, { fg = palette.bg_alt } },
  { 'TelescopePromptNormal', bg = palette.bg_alt, { fg = palette.orange } },
  { 'TelescopeResultsBorder', bg = palette.bg_alt, { fg = palette.bg_alt } },
  { 'TelescopePreviewBorder', bg = palette.bg_alt, { fg = palette.bg_alt } },
  { 'TelescopeResultsNormal', { fg = palette.fg } },
  { 'TelescopeSelectionCaret', { fg = palette.yellow } },
  { 'TelescopeMatching', { fg = palette.yellow } },
  { 'CursorWord', { bg = palette.bg_alt } },
  { 'IndentLine', { link = 'LineNr' } },
  { 'SagaVariable', { fg = palette.green } },
  { 'RapidFinished', { fg = palette.red, bold = true } },
  { 'RapidTake', { fg = palette.purple, bold = true } },
  { 'RapidDate', { fg = palette.purple, bold = true } },
  { 'RapidFile', { fg = palette.blue, bold = true } },
  { 'RapidTargetPos', { fg = palette.teal, bold = true } },
  { 'LspSignatureActiveParameter', { fg = palette.yellow, underline = true } },
  { 'netrwTreeBar', { link = 'Comment' } },
}

local g, api, opt = vim.g, vim.api, vim.opt
g.terminal_color_0 = palette.bg
g.terminal_color_1 = palette.red
g.terminal_color_2 = palette.green
g.terminal_color_3 = palette.yellow
g.terminal_color_4 = palette.blue
g.terminal_color_5 = palette.purple
g.terminal_color_6 = palette.cyan
g.terminal_color_7 = palette.fg
g.terminal_color_8 = palette.fg_dim
g.terminal_color_9 = palette.red
g.terminal_color_10 = palette.green
g.terminal_color_11 = palette.yellow
g.terminal_color_12 = palette.blue
g.terminal_color_13 = palette.purple
g.terminal_color_14 = palette.cyan
g.terminal_color_15 = palette.fg

api.nvim_command('hi clear')
opt.background = 'dark'
g.colors_name = 'night'
opt.termguicolors = true
for _, v in pairs(groups) do
  api.nvim_set_hl(0, v[1], v[2])
end
