local palette = {
  fg = '#F8F8F2',
  bg = '#282A36',
  bglighter = '#424450',
  bglight = '#343746',
  bgdark = '#21222C',
  bgdarker = '#191A21',
  comment = '#6272A4',
  selection = '#44475A',
  subtle = '#424450',
  cyan = '#8BE9FD',
  green = '#50FA7B',
  teal = '#47b38f',
  orange = '#FFB86C',
  pink = '#FF79C6',
  purple = '#BD93F9',
  red = '#FF5555',
  yellow = '#F1FA8C',
  none = 'NONE',
}

local groups = {
  { 'Normal', { fg = palette.fg, bg = palette.bg } },
  { 'SignColumn', { bg = palette.bg } },
  { 'LineNr', { fg = palette.comment } },
  { 'EndOfBuffer', { fg = palette.bg, bg = palette.none } },
  { 'Search', { fg = palette.green, reverse = true } },
  { 'Visual', { bg = palette.selection } },
  { 'ColorColumn', { bg = palette.bgdark } },
  { 'Whitespace', { fg = palette.bglighter } },
  { 'VertSplit', { fg = palette.comment, bg = palette.bgdark } },
  { 'Title', { fg = palette.green, bold = true } },
  { 'Cursorline', { bg = palette.subtle } },
  { 'CursorLineNr', { fg = palette.yellow } },
  { 'Pmenu', { bg = palette.bgdark } },
  { 'PmenuSel', { bg = palette.selection } },
  { 'PmenuSbar', { fg = '#586e75' } },
  { 'PmenuThumb', { bg = palette.bg } },
  { 'PmenuKind', { bg = palette.bgdarker, fg = palette.yellow } },
  { 'PmenuKindSel', { link = 'PmenuSel' } },
  { 'PmenuExtra', { link = 'Pmenu' } },
  { 'PmenuExtraSel', { link = 'PmenuSel' } },
  { 'WildMenu', { link = 'Pmenu' } },
  { 'StatusLine', { bg = palette.bglighter, bold = true } },
  { 'StatusLineNC', { bg = palette.bglight } },
  { 'WinBar', { bg = palette.none } },
  { 'WinBarNC', { bg = palette.none } },
  { 'Error', { fg = palette.red, bold = true } },
  { 'ErrorMsg', { link = 'Error' } },
  { 'TODO', { fg = palette.cyan } },
  { 'Conceal', { fg = palette.purple, bg = palette.none } },
  { 'NonText', { link = 'Comment' } },
  { 'FloatBorder', { fg = palette.purple } },
  { 'FloatNormal', { link = 'Normal' } },
  { 'FloatShadow', { bg = palette.bglight } },
  { 'Folded', { fg = palette.bg, bold = true } },
  { 'FoldColumn', { link = 'SignColumn' } },
  { 'SpellBad', { fg = palette.red } },
  { 'SpellCap', { undercurl = true, fg = palette.red } },
  { 'SpellRare', { undercurl = true, fg = palette.purple } },
  { 'SpellLocal', { undercurl = true } },
  { 'WarningMsg', { fg = palette.red } },
  { 'MoreMsg', { fg = palette.green } },
  { 'NvimInternalError', { fg = palette.red } },
  { 'Directory', { fg = palette.purple } },
  { 'Identifier', { fg = palette.purple } },
  { '@variable', { fg = palette.fg } },
  { '@variable.builtin', { fg = palette.purple } },
  { 'Constant', { fg = palette.orange } },
  { '@constant.builtin', { link = 'Constant' } },
  { '@constant.macro', { link = 'Constant' } },
  { '@namespace', { fg = palette.cyan } },
  { 'Keyword', { fg = palette.pink } },
  { '@keyword.function', { link = 'Keyword' } },
  { '@keyword.return', { link = 'Keyword' } },
  { '@keyword.operator', { link = 'Operator' } },
  { 'Conditional', { link = 'Keyword' } },
  { 'Repeat', { link = 'Conditional' } },
  { 'Debug', { fg = palette.orange } },
  { 'Label', { fg = palette.purple } },
  { 'PreProc', { fg = palette.purple } },
  -- { 'Include', { link = 'PreProc' } },
  { 'Include', { link = 'Keyword' } },
  { 'Exception', { fg = palette.purple } },
  { 'Statement', { fg = palette.purple } },
  { 'SpecialKey', { fg = palette.orange } },
  { 'Special', { fg = palette.orange } },
  { 'Type', { fg = palette.orange } },
  { '@type.builtin', { link = 'Type' } },
  { '@type.definition', { link = 'Type' } },
  { '@type.qualifier', { link = 'KeyWord' } },
  { '@storageclass', { link = 'KeyWord' } },
  { '@field', { fg = palette.fg } },
  { '@property', { link = '@field' } },
  { 'Function', { fg = palette.green } },
  { '@function.builtin', { link = 'Function' } },
  { '@function.call', { link = 'Function' } },
  { '@function.macro', { link = 'Function' } },
  { '@method', { link = 'Function' } },
  { '@method.call', { link = 'Function' } },
  { '@constructor', { fg = palette.purple } },
  -- { '@parameter', { fg = palette.orange} },
  { '@parameter', { link = '@variable' } },
  { 'String', { fg = palette.yellow } },
  { 'Number', { fg = palette.purple } },
  { 'Float', { link = 'Number' } },
  { 'Boolean', { link = 'Constant' } },
  { 'Define', { link = 'PreProc' } },
  { 'Operator', { fg = palette.pink } },
  { 'Comment', { fg = palette.comment } },
  { '@punctuation.bracket', { fg = palette.fg } },
  { '@punctuation.delimiter', { fg = palette.fg } },
  { '@tag.html', { fg = palette.orange } },
  { '@tag.attribute.html', { link = '@property' } },
  { '@tag.delimiter.html', { link = '@punctuation.delimiter' } },
  { '@tag.javascript', { link = '@tag.html' } },
  { '@tag.attribute.javascript', { link = '@tag.attribute.html' } },
  { '@tag.delimiter.javascript', { link = '@tag.delimiter.html' } },
  { '@tag.typescript', { link = '@tag.html' } },
  { '@tag.attribute.typescript', { link = '@tag.attribute.html' } },
  { '@tag.delimiter.typescript', { link = '@tag.delimiter.html' } },
  { '@text.reference.markdown_inline', { fg = palette.purple } },
  { 'DiffAdd', { fg = palette.green, bg = palette.none } },
  { 'DiffChange', { fg = palette.purple } },
  { 'DiffDelete', { fg = palette.orange } },
  { 'DiffText', { fg = palette.orange } },
  { '@text.diff.add.diff', { link = 'DiffAdd' } },
  { '@text.diff.delete.diff', { link = 'DiffDelete' } },
  { '@text.diff.change.diff', { link = 'DiffChange' } },
  { 'DiagnosticError', { link = 'Error' } },
  { 'DiagnosticWarn', { fg = palette.yellow } },
  { 'DiagnosticInfo', { fg = palette.purple } },
  { 'DiagnosticHint', { fg = palette.cyan } },
  { 'DiagnosticSignError', { link = 'DiagnosticError' } },
  { 'DiagnosticSignWarn', { link = 'DiagnosticWarn' } },
  { 'DiagnosticSignInfo', { link = 'DiagnosticInfo' } },
  { 'DiagnosticSignHint', { link = 'DiagnosticHint' } },
  { 'DiagnosticUnderlineError', { undercurl = true } },
  { 'DiagnosticUnderlineWarn', { undercurl = true } },
  { 'DiagnosticUnderlineInfo', { undercurl = true } },
  { 'DiagnosticUnderlineHint', { undercurl = true } },
  { 'GitGutterAdd', { fg = palette.green } },
  { 'GitGutterChange', { fg = palette.purple } },
  { 'GitGutterDelete', { fg = palette.red } },
  { 'GitGutterChangeDelete', { fg = palette.red } },
  { 'TelescopePromptBorder', bg = palette.bglight, { fg = palette.bglight } },
  { 'TelescopePromptNormal', bg = palette.bglight, { fg = palette.orange } },
  { 'TelescopeResultsBorder', bg = palette.bglight, { fg = palette.bglight } },
  { 'TelescopePreviewBorder', bg = palette.bglight, { fg = palette.bglight } },
  { 'TelescopeResultsNormal', { fg = palette.fg } },
  { 'TelescopeSelectionCaret', { fg = palette.yellow } },
  { 'TelescopeMatching', { fg = palette.yellow } },
  { 'CursorWord', { bg = palette.bglight } },
  { 'IndentLine', { link = 'LineNr' } },
  { 'SagaVariable', { fg = palette.green } },
  { 'RapidFinished', { fg = palette.red, bold = true } },
  { 'RapidTake', { fg = palette.purple, bold = true } },
  { 'RapidDate', { fg = palette.purple, bold = true } },
  { 'RapidFile', { fg = palette.purple, bold = true } },
  { 'RapidTargetPos', { fg = palette.green, bold = true } },
  { 'LspSignatureActiveParameter', { fg = palette.yellow, underline = true } },
}

local g, api, opt = vim.g, vim.api, vim.opt
g.terminal_color_0 = palette.bg
g.terminal_color_1 = palette.red
g.terminal_color_2 = palette.green
g.terminal_color_3 = palette.yellow
g.terminal_color_4 = palette.purple
g.terminal_color_5 = palette.purple
g.terminal_color_6 = palette.cyan
g.terminal_color_7 = palette.fg
g.terminal_color_8 = palette.fg_dim
g.terminal_color_9 = palette.red
g.terminal_color_10 = palette.green
g.terminal_color_11 = palette.yellow
g.terminal_color_12 = palette.purple
g.terminal_color_13 = palette.purple
g.terminal_color_14 = palette.cyan
g.terminal_color_15 = palette.fg
api.nvim_command('hi clear')
opt.background = 'dark'
opt.termguicolors = true
for _, v in pairs(groups) do
  api.nvim_set_hl(0, v[1], v[2])
end
