confirm_os_window_close 0
update_check_interval 0
cursor_shape block
cursor_blink_interval 0
enable_audio_bell no
mouse_hide_wait 3.0
hide_window_decorations titlebar-only
enabled_layouts splits
tab_bar_edge top
tab_title_template "{fmt.fg.c2c2c2}{title}"
active_tab_title_template "◉ {index}: {title}"
remember_window_size yes
initial_window_width 1280
initial_window_height 800

font_size 14
font_family SF Mono
# Chinese
symbol_map U+4E00-U+9FFF LXGW WenKai Mono
#symbol_map U+4E00-U+9FFF JLB
# Nerd Fonts
symbol_map  U+E000-U+E00D,U+e0a0-U+e0a2,U+e0b0-U+e0b3,U+e0a3-U+e0a3,U+e0b4-U+e0c8,U+e0cc-U+e0d2,U+e0d4-U+e0d4,U+e5fa-U+e62b,U+e700-U+e7c5,U+f000-U+f2e0,U+e200-U+e2a9,U+eb45,U+eb72,U+ebc5,U+f400-U+f4a8,U+2665-U+2665,U+f27c-U+f27c,U+F300-U+F313,U+23fb-U+23fe,U+2b58-U+2b58,U+f500-U+fd46,U+e300-U+e3eb,U+ea85,U+eb99,U+eb13,U+ea86,U+21B5,U+25B8,U+2605,U+2630,U+2632,U+2714,U+E0A3,U+E615,U+E62B,U+eb70,U+ea88,U+ebdd,U+eb44,U+eb27,U+eb2f,U+ead8,U+eb99,U+eb29 Symbols Nerd Font

include themes_light.conf
